version: '3.4'

services:
  db:
    image: mysql:9.0.1
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT=root
      - MYSQL_DATABASE=development
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - bundle:/usr/local/bundle
      - .:/rails
    links:
      - db
    ports:
      - 3000:3000
    command: "bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'"
    environment:
      - DB_HOST=db

volumes:
  bundle:
    name: bundle
